### ISSUE TITLE
Homework is uncountable

### ISSUE THREAD

**Issue by brona-ruzicka** [PanJohnny/Baka4J#2]
This is just a naming mistake.

I've seen the use of the word 'homeworks' in the names of functions and elsewhere. However the word 'work' and therefore even the word 'homework' are uncountable. Meaning that they don't have a plural form, e.a. you can't use the form 'homeworks', instead you should use 'homework' or for example 'assignments'.

However since even the (un)official endpoint is named 'homeworks'. It is up for debate whether or not to use different naming scheme here. That said, I would still probably recommend to replace 'homeworks' with 'assignments'.

**Comment by PanJohnny** [comment]
I plan to work on this. But I am kinda busy right now. This project has low priority, because it is unused by me. You are right with the naming thing and how I did it. Thanks for the issue, when I'll look into this project I'll fix it.

**Comment by PanJohnny** [comment]
So... I am working on rework of this project. I decided that I will name the method assignements. Thank you for disclosing this matter.
